export const enum CategoryType {
  BILL = "BILL",
  ENTERTAINMENT = "ENTERTAINMENT",
  FOOD_DINING = "FOOD DINING",
  FEES_CHARGES = "FEES CHARGES",
  INCOME = "INCOME",
  TRAVEL = "TRAVEL",
  HOME = "HOME",
  TAXES = "TAXES",
  SHOPPING = "SHOPPING",
  MISC = "MISC",
  HIDE_FROM_BUDGET = "HIDE FROM BUDGET",
  EDUCATION = "EDUCATION"
}
